name: Deploy Production

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: 22.19.0
          cache: "npm"
      - name: Create .env file
        run: printf '%b' "${{ secrets.ENV_PRODUCTION }}" > .env
      - run: npm i --force
      - run: npm run build
      - name: send telegram message on build success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_thread_id: ${{ secrets.TELEGRAM_THREAD }}
          message: |
            🚀 Build completed! 🟢
            👤 Actor: ${{ github.actor }}
            📦 Repository: ${{ github.repository }}
            📝 Commit: ${{ github.event.commits[0].message }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: send telegram message on build failed
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_thread_id: ${{ secrets.TELEGRAM_THREAD }}
          message: |
            🚀 Build failed! 🔴
            👤 Actor: ${{ github.actor }}
            📦 Repository: ${{ github.repository }}
            📝 Commit: ${{ github.event.commits[0].message }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.19.0
          cache: "npm"
      - run: npm i --force
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.5
        env:
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          envs: ENV_PRODUCTION
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/english-lms
            git fetch --all
            git reset --hard origin/main
            printf '%s' "$ENV_PRODUCTION" > .env
            npm i --force
            npx prisma generate
            npm run build
            pm2 restart "E-Learning Platform"
      - name: send telegram message on deploy success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_thread_id: ${{ secrets.TELEGRAM_THREAD }}
          message: |
            🚀 Deploy completed! 🟢
            👤 Actor: ${{ github.actor }}
            📦 Repository: ${{ github.repository }}
            📝 Commit: ${{ github.event.commits[0].message }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: send telegram message on deploy failed
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_thread_id: ${{ secrets.TELEGRAM_THREAD }}
          message: |
            🚀 Deploy failed! 🔴
            👤 Actor: ${{ github.actor }}
            📦 Repository: ${{ github.repository }}
            📝 Commit: ${{ github.event.commits[0].message }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
